# -*- coding: utf-8 -*-
"""2108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YsEswcSMgEcsydO-50YBFzyCqSxmQI6
"""

import sys
from collections import Counter

n = int(sys.stdin.readline())
a = [int(sys.stdin.readline()) for _ in range(n)]

# 산술평균
print(round(sum(a) / n))

# 중앙값
a_sorted = sorted(a)
print(a_sorted[n // 2])

# 최빈값
count = Counter(a)
max_frequency = max(count.values())
fq = [num for num, freq in count.items() if freq == max_frequency]
print(sorted(fq)[0] if len(fq) == 1 else sorted(fq)[1])

# 범위
print(max(a) - min(a))

