# -*- coding: utf-8 -*-
"""25192.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNpH8M1ny6QhqaYsoXn6-CxPkKaj_xQ-
"""

N=int(input())

dic={}

cnt=0

for _ in range(N):
    Input=input()

    if Input=="ENTER":
        for key,value in dic.items():
            if value==1:
                cnt+=1
        dic={}
    else:
        if Input not in dic:
            dic[Input]=1

for key,value in dic.items():
    if value==1:
        cnt+=1

print(cnt)

