# -*- coding: utf-8 -*-
"""2720

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Ro01y1ikRJ6LBUDrX62sONQ4EZpL1sa
"""

t = int(input())
for i in range(t):
    n = int(input())
    quarters = n // 25
    n %= 25
    dimes = n // 10
    n %= 10
    nickels = n // 5
    n %= 5
    pennies = n // 1
    print(quarters, dimes, nickels, pennies)