# -*- coding: utf-8 -*-
"""백준.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfNTxyq45rEnXbay5JbTv4gYzSQWD7va
"""

#백준 [Python] 백준 알고리즘 온라인 저지 2292번 : 벌집

n = int(input())

nums_pileup = 1  # 벌집의 개수, 1개부터 시작
cnt = 1
while n > nums_pileup :
    nums_pileup += 6 * cnt  # 벌집이 6의 배수로 증가
    cnt += 1  # 반복문을 반복하는 횟수
print(cnt)