# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VZ_No80rXK_YUdN-xkwPqs2wIqCDUNR
"""

a = int(input())
b = int(input())
print(a*b)